//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnzHogwards
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetId { get; set; }
        public string PetName { get; set; }
        public string Species { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ProfessorId { get; set; }
        public string OwnerName => Student != null ? $"{Student.FirstName} {Student.LastName}" : Professor != null ? $"{Professor.FirstName} {Professor.LastName}" : "(Sahip yok)";
        public virtual Professor Professor { get; set; }
        public virtual Student Student { get; set; }
    }
}
