//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnzHogwards
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WandMaintenanceAlert
    {
        [Key]
        public int AlertId { get; set; }
        public int WandId { get; set; }
        public System.DateTime AlertDate { get; set; }
        public string Message { get; set; }
    
        public virtual Wand Wand { get; set; }
    }
}
