//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogwarts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetId { get; set; }
        public string PetName { get; set; }
        public string Species { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ProfessorId { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual Student Student { get; set; }
    }
}
