//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogwarts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spell
    {
        public int SpellId { get; set; }
        public string SpellName { get; set; }
        public string Effect { get; set; }
        public int RequiredLevel { get; set; }
    }
}
