//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogwarts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wand()
        {
            this.Students = new HashSet<Student>();
            this.WandMaintenanceAlerts = new HashSet<WandMaintenanceAlert>();
        }
    
        public int WandId { get; set; }
        public string Core { get; set; }
        public string Material { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastMaintenanceDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WandMaintenanceAlert> WandMaintenanceAlerts { get; set; }
    }
}
