//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdHogwarts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HogwardsEntities : DbContext
    {
        public HogwardsEntities()
            : base("name=HogwardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Spell> Spells { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Wand> Wands { get; set; }
        public virtual DbSet<WandMaintenanceAlert> WandMaintenanceAlerts { get; set; }
    }
}
